CREATE TABLE TAB_DRIVERS 
(
    ID_DRIVERS NUMBER NOT NULL,
    EMPLOYEE_NUMBER NUMBER(15) NOT NULL,
    FULLNAME VARCHAR(55) NOT NULL,
    
	CONSTRAINT PK_TAB_DRIVERS PRIMARY KEY (ID_DRIVERS)
);

CREATE SEQUENCE Tab_Drivers_Sequence START WITH 1 INCREMENT BY 1;

CREATE TRIGGER TAB_DRIVERS_Trigger BEFORE INSERT ON TAB_DRIVERS FOR EACH ROW
BEGIN
  SELECT TAB_DRIVERS_SEQUENCE.NEXTVAL 
  INTO :new.ID_DRIVERS
  FROM dual;
END;


CREATE TABLE TAB_TYPES_OF_VEHICLES
(
    ID_TYPES_OF_TAB_VEHICLES NUMBER NOT NULL,
    DESCRIPTION VARCHAR(30) NOT NULL,
	SPECIAL_QUALIFICATION VARCHAR(1) NOT NULL,
    
	CONSTRAINT PK_TAB_TYPES_OF_VEHICLES PRIMARY KEY (ID_TYPES_OF_TAB_VEHICLES),
	CONSTRAINT CK_SPECIAL_QUALIFICATION CHECK (SPECIAL_QUALIFICATION in ('S', 'N'))
);

CREATE SEQUENCE TAB_TYPES_OF_VEHICLES_Sequence START WITH 1 INCREMENT BY 1;
  
CREATE OR REPLACE TRIGGER TAB_TYPES_OF_VEHICLES_Trigger BEFORE INSERT ON TAB_TYPES_OF_VEHICLES FOR EACH ROW
BEGIN
  SELECT TAB_TYPES_OF_VEHICLES_Sequence.NEXTVAL 
  INTO :new.ID_TAB_TYPES_OF_VEHICLES
  FROM dual;
END;


CREATE TABLE TAB_VEHICLES 
(
    ID_VEHICLE NUMBER NOT NULL,
    REGISTRATION_NUMBER NUMBER(15) NOT NULL,
    PLATE VARCHAR(7) NOT NULL,
	STATUS VARCHAR(10) NOT NULL,
	MILEAGE NUMBER NOT NULL,
	MODEL NUMBER NOT NULL,
	CURRENT_VALUE NUMBER,
	REPLACEMENT_VALUE NUMBER,
	TAXED_DATE DATE,
	BOUGHT_DATE DATE,
	POLICY_NUMBER NUMBER,
	WRITTEN_OFF VARCHAR(1) NOT NULL,
	ID_TAB_TYPES_OF_VEHICLES NUMBER NOT NULL,
	CONSTRAINT PK_TAB_VEHICLES PRIMARY KEY (ID_VEHICLE),
	CONSTRAINT FK_VEHICLE_TYPE FOREIGN KEY (ID_TYPES_OF_TAB_VEHICLES) REFERENCES TAB_TYPES_OF_VEHICLES(ID_TYPES_OF_TAB_VEHICLES),
	CONSTRAINT CK_STATUS CHECK (STATUS in ('Active', 'Inactive', 'Repairing', 'Sold')),
	CONSTRAINT CK_WRITTEN_OFF CHECK (WRITTEN_OFF in ('S', 'N'))
);

CREATE SEQUENCE TAB_VEHICLES_Secuence START WITH 1 INCREMENT BY 1;
  
CREATE OR REPLACE TRIGGER TAB_VEHICLES_Trigger BEFORE INSERT ON TAB_VEHICLES FOR EACH ROW
BEGIN
  SELECT TAB_VEHICLES_Secuence.NEXTVAL 
  INTO :new.ID_VEHICLE
  FROM dual;
END;

CREATE TABLE TAB_DRIVERS_VEHICLES 
(
    ID_DRIVERS NUMBER NOT NULL,
    ID_VEHICLE NUMBER NOT NULL,
	CONSTRAINT PK_TAB_DRIVERS_VEHICLES PRIMARY KEY (ID_DRIVERS, ID_VEHICLE),
	CONSTRAINT FK_TAB_DRIVERS_VEHICLES_Driver FOREIGN KEY (ID_DRIVERS) REFERENCES TAB_VEHICLES(ID_VEHICLE),
	CONSTRAINT FK_TAB_DRIVERS_VEHICLES_Vehicle FOREIGN KEY (ID_VEHICLE) REFERENCES TAB_DRIVERS(ID_DRIVERS)
);


CREATE TABLE TAB_DRIVERS_QUALIFICATIONS 
(
    ID_DRIVERS NUMBER NOT NULL,
    TYPE_VEHICLE NUMBER NOT NULL,
	STATUS VARCHAR(15) NOT NULL,
	ASSIGNMENT_DATE DATE NOT NULL,
	CONSTRAINT PK_TAB_DRIVERS_QUALIFICATIONS PRIMARY KEY (ID_DRIVERS, TYPE_VEHICLE),
	CONSTRAINT FK_Qualification_Driver FOREIGN KEY (ID_DRIVERS) REFERENCES TAB_DRIVERS(ID_DRIVERS),
	CONSTRAINT FK_Qualification_TYPE_VEHICLE FOREIGN KEY (TYPE_VEHICLE) REFERENCES TYPE_VEHICLE(ID_TYPES_OF_TAB_VEHICLES),
	CONSTRAINT CK_status_qualification CHECK (STATUS in ('Active', 'Inactive', 'Expired', 'Disqualified'))
);

CREATE TABLE TAB_REPAIR_COSTS 
(
    ID_REPAIR_COSTS NUMBER NOT NULL,
    ID_VEHICLE NUMBER NOT NULL,
	REPAIR_DATE DATE NOT NULL,
	DESCRIPTION VARCHAR(100),
	AMOUNT NUMBER(19,4) NOT NULL,
	STATUS VARCHAR(10) NOT NULL,	
	CONSTRAINT PK_TAB_REPAIR_COSTS PRIMARY KEY (ID_REPAIR_COSTS),
	CONSTRAINT FK_Repair_Vehicle FOREIGN KEY (ID_VEHICLE) REFERENCES TAB_VEHICLES(ID_VEHICLE),
	CONSTRAINT CK_Repair_Status CHECK (STATUS in ('Pending', 'Paid'))
);

CREATE SEQUENCE TAB_REPAIR_COSTS_Sequence START WITH 1 INCREMENT BY 1;

CREATE OR REPLACE TRIGGER TAB_REPAIR_COSTS_Trigger BEFORE INSERT ON TAB_REPAIR_COSTS FOR EACH ROW
BEGIN
  SELECT TAB_REPAIR_COSTS_Sequence.NEXTVAL 
  INTO :new.ID_REPAIR_COSTS
  FROM dual;
END;

CREATE TABLE TAB_INSURANCE_CLAIMS 
(
    ID_INSURANCE_CLAIMS NUMBER NOT NULL,
    ID_VEHICLE NUMBER NOT NULL,
	POLICY NUMBER NOT NULL,
	LOSS_DATE DATE NOT NULL,
	ISSUE_DATE DATE NOT NULL,
	NATURE_PAYMENT VARCHAR(100),
	DAMAGES VARCHAR(500),
	CONSTRAINT PK_TAB_INSURANCE_CLAIMS PRIMARY KEY (ID_INSURANCE_CLAIMS),
	CONSTRAINT FK_Insurance_Vehicle FOREIGN KEY (ID_VEHICLE) REFERENCES TAB_VEHICLES(ID_VEHICLE)
);


CREATE SEQUENCE TAB_INSURANCE_CLAIMS_Sequence START WITH 1 INCREMENT BY 1;
  
CREATE OR REPLACE TRIGGER TAB_INSURANCE_CLAIMS_Trigger BEFORE INSERT ON TAB_INSURANCE_CLAIMS FOR EACH ROW
BEGIN
  SELECT TAB_INSURANCE_CLAIMS_Sequence.NEXTVAL 
  INTO :new.ID_INSURANCE_CLAIMS
  FROM dual;
END;


CREATE TABLE TAB_SERVICES 
(
    ID_SERVICE NUMBER NOT NULL,
    ID_VEHICLE NUMBER NOT NULL,
	NAME VARCHAR(50) NOT NULL,
	ISSUE_DATE DATE NOT NULL,
	DESCRIPTION VARCHAR(100),
	STATUS VARCHAR(30) NOT NULL,	
	CONSTRAINT PK_TAB_SERVICES PRIMARY KEY (ID_SERVICE),
	CONSTRAINT FK_Service_Vehicle FOREIGN KEY (ID_VEHICLE) REFERENCES TAB_VEHICLES(ID_VEHICLE),
	CONSTRAINT CK_Service_Status CHECK (STATUS in ('Pending', 'Scheduled', 'Ok'))
);

CREATE SEQUENCE TAB_SERVICES_Sequence START WITH 1 INCREMENT BY 1;
  

CREATE OR REPLACE TRIGGER TAB_SERVICES_Trigger BEFORE INSERT ON TAB_SERVICES FOR EACH ROW
BEGIN
  SELECT TAB_SERVICES_Sequence.NEXTVAL 
  INTO :new.ID_SERVICE
  FROM dual;
END;


CREATE TABLE TAB_TYPES_TAB_SERVICES 
(
    ID_TYPES_TAB_SERVICES NUMBER NOT NULL,
    DESCRIPTION VARCHAR(100) NOT NULL,
	CONSTRAINT PK_TAB_TYPES_TAB_SERVICES PRIMARY KEY (ID_TYPES_TAB_SERVICES)
);

CREATE SEQUENCE TAB_TYPES_TAB_SERVICES_Sequence START WITH 1 INCREMENT BY 1;


CREATE OR REPLACE TRIGGER TAB_TYPES_TAB_SERVICES_Trigger BEFORE INSERT ON TAB_TYPES_TAB_SERVICES FOR EACH ROW
BEGIN
  SELECT TAB_TYPES_TAB_SERVICES_Sequence.NEXTVAL 
  INTO :new.ID_TYPES_TAB_SERVICES
  FROM dual;
END;

CREATE TABLE TAB_TAB_SERVICES_DETAILS 
(
    ID_TAB_SERVICES_DETAILS NUMBER NOT NULL,
    ID_SERVICE NUMBER NOT NULL,
	TYPE_SERVICE NUMBER NOT NULL,
	STATUS VARCHAR(15) NOT NULL,	
	CONSTRAINT PK_TAB_TAB_SERVICES_DETAILS PRIMARY KEY (ID_TAB_SERVICES_DETAILS),
	CONSTRAINT FK_Service FOREIGN KEY (ID_SERVICE) REFERENCES TAB_SERVICES(ID_SERVICE),
	CONSTRAINT FK_TYPE_SERVICE FOREIGN KEY (TYPE_SERVICE) REFERENCES TAB_TYPES_TAB_SERVICES(ID_TYPES_TAB_SERVICES),
	CONSTRAINT CK_STATUS CHECK (STATUS in ('Ok', 'Pending', 'Needs Repair', 'Observations'))
);
 
CREATE SEQUENCE TAB_TAB_SERVICES_DETAILS_Sequence START WITH 1 INCREMENT BY 1;
    
CREATE OR REPLACE TRIGGER TAB_TAB_SERVICES_DETAILS_Trigger BEFORE INSERT ON TAB_TAB_SERVICES_DETAILS FOR EACH ROW
BEGIN
  SELECT TAB_TAB_SERVICES_DETAILS_Sequence.NEXTVAL 
  INTO :new.ID_TAB_SERVICES_DETAILS
  FROM dual;
END;





INSERT INTO TBA_DRIVERS (EMPLOYEE_NUMBER,FULLNAME) VALUES ('1684031467199','Richard Wiley');
INSERT INTO TBA_DRIVERS (EMPLOYEE_NUMBER,FULLNAME) VALUES ('1640051322199','Abel Love');
INSERT INTO TBA_DRIVERS (EMPLOYEE_NUMBER,FULLNAME) VALUES ('1643111764399','Chadwick Higgins');
INSERT INTO TBA_DRIVERS (EMPLOYEE_NUMBER,FULLNAME) VALUES ('1690072649599','Bradley Oliver');
INSERT INTO TBA_DRIVERS (EMPLOYEE_NUMBER,FULLNAME) VALUES ('1643071257299','Josiah Grimes');
INSERT INTO TBA_DRIVERS (EMPLOYEE_NUMBER,FULLNAME) VALUES ('1627012684299','Forrest Carney');
INSERT INTO TBA_DRIVERS (EMPLOYEE_NUMBER,FULLNAME) VALUES ('1631072552299','Cooper Abbott');
INSERT INTO TBA_DRIVERS (EMPLOYEE_NUMBER,FULLNAME) VALUES ('1661032999699','Isaiah Velasquez');
INSERT INTO TBA_DRIVERS (EMPLOYEE_NUMBER,FULLNAME) VALUES ('1698072001599','Rudyard Nieves');
INSERT INTO TBA_DRIVERS (EMPLOYEE_NUMBER,FULLNAME) VALUES ('1683010930799','Zane Acosta');
INSERT INTO TBA_DRIVERS (EMPLOYEE_NUMBER,FULLNAME) VALUES ('1638022320899','Driscoll Villarreal');
INSERT INTO TBA_DRIVERS (EMPLOYEE_NUMBER,FULLNAME) VALUES ('1627010703099','Dolan Pacheco');
INSERT INTO TBA_DRIVERS (EMPLOYEE_NUMBER,FULLNAME) VALUES ('1665010849899','Scott Bartlett');
INSERT INTO TBA_DRIVERS (EMPLOYEE_NUMBER,FULLNAME) VALUES ('1662112127099','Lyle Francis');
INSERT INTO TBA_DRIVERS (EMPLOYEE_NUMBER,FULLNAME) VALUES ('1685092698099','Caleb Cobb');
INSERT INTO TBA_DRIVERS (EMPLOYEE_NUMBER,FULLNAME) VALUES ('1618052167399','Rahim Morrow');
INSERT INTO TBA_DRIVERS (EMPLOYEE_NUMBER,FULLNAME) VALUES ('1642023034599','Brandon Patel');
INSERT INTO TBA_DRIVERS (EMPLOYEE_NUMBER,FULLNAME) VALUES ('1600010679999','Rafael Cox');
INSERT INTO TBA_DRIVERS (EMPLOYEE_NUMBER,FULLNAME) VALUES ('1627082905999','Craig Dunlap');
INSERT INTO TBA_DRIVERS (EMPLOYEE_NUMBER,FULLNAME) VALUES ('1641100153999','Jonas Mccray');
INSERT INTO TBA_DRIVERS (EMPLOYEE_NUMBER,FULLNAME) VALUES ('1649012570899','Lucian Hudson');
INSERT INTO TBA_DRIVERS (EMPLOYEE_NUMBER,FULLNAME) VALUES ('1675010143799','Stone Sullivan');
INSERT INTO TBA_DRIVERS (EMPLOYEE_NUMBER,FULLNAME) VALUES ('1679110972599','Cairo Booker');
INSERT INTO TBA_DRIVERS (EMPLOYEE_NUMBER,FULLNAME) VALUES ('1619120135399','Boris Nash');
INSERT INTO TBA_DRIVERS (EMPLOYEE_NUMBER,FULLNAME) VALUES ('1676070848799','Nasim Burton');
INSERT INTO TBA_DRIVERS (EMPLOYEE_NUMBER,FULLNAME) VALUES ('1674060205299','Colton Crawford');
INSERT INTO TBA_DRIVERS (EMPLOYEE_NUMBER,FULLNAME) VALUES ('1638020151299','Silas Dominguez');
INSERT INTO TBA_DRIVERS (EMPLOYEE_NUMBER,FULLNAME) VALUES ('1670060404599','Chancellor Richards');
INSERT INTO TBA_DRIVERS (EMPLOYEE_NUMBER,FULLNAME) VALUES ('1669071038499','Zane Hendrix');
INSERT INTO TBA_DRIVERS (EMPLOYEE_NUMBER,FULLNAME) VALUES ('1626051005099','Drake Dalton');
INSERT INTO TBA_DRIVERS (EMPLOYEE_NUMBER,FULLNAME) VALUES ('1626092749599','Lucius Pitts');
INSERT INTO TBA_DRIVERS (EMPLOYEE_NUMBER,FULLNAME) VALUES ('1600112484799','Dexter Coffey');
INSERT INTO TBA_DRIVERS (EMPLOYEE_NUMBER,FULLNAME) VALUES ('1607021008299','Jelani Davis');
INSERT INTO TBA_DRIVERS (EMPLOYEE_NUMBER,FULLNAME) VALUES ('1689112009999','Rahim Vazquez');
INSERT INTO TBA_DRIVERS (EMPLOYEE_NUMBER,FULLNAME) VALUES ('1693071487099','Emmanuel Montgomery');
INSERT INTO TBA_DRIVERS (EMPLOYEE_NUMBER,FULLNAME) VALUES ('1620052393099','Hayden Whitfield');
INSERT INTO TBA_DRIVERS (EMPLOYEE_NUMBER,FULLNAME) VALUES ('1639080499199','Lamar Garrett');
INSERT INTO TBA_DRIVERS (EMPLOYEE_NUMBER,FULLNAME) VALUES ('1634022085399','Donovan Frye');
INSERT INTO TBA_DRIVERS (EMPLOYEE_NUMBER,FULLNAME) VALUES ('1607112165999','Plato Tillman');
INSERT INTO TBA_DRIVERS (EMPLOYEE_NUMBER,FULLNAME) VALUES ('1697081404699','Chadwick Delgado');
INSERT INTO TBA_DRIVERS (EMPLOYEE_NUMBER,FULLNAME) VALUES ('1668023004699','Joel Cohen');
INSERT INTO TBA_DRIVERS (EMPLOYEE_NUMBER,FULLNAME) VALUES ('1618060603699','Cade Robertson');
INSERT INTO TBA_DRIVERS (EMPLOYEE_NUMBER,FULLNAME) VALUES ('1665122283799','Laith Dalton');
INSERT INTO TBA_DRIVERS (EMPLOYEE_NUMBER,FULLNAME) VALUES ('1623041206699','Axel Ryan');
INSERT INTO TBA_DRIVERS (EMPLOYEE_NUMBER,FULLNAME) VALUES ('1616050182099','Jesse Short');
INSERT INTO TBA_DRIVERS (EMPLOYEE_NUMBER,FULLNAME) VALUES ('1634032239999','Abbot Sanford');
INSERT INTO TBA_DRIVERS (EMPLOYEE_NUMBER,FULLNAME) VALUES ('1669092452299','Xander Palmer');
INSERT INTO TBA_DRIVERS (EMPLOYEE_NUMBER,FULLNAME) VALUES ('1669110812299','Garrett Estrada');
INSERT INTO TBA_DRIVERS (EMPLOYEE_NUMBER,FULLNAME) VALUES ('1662012850899','Brandon Burnett');
INSERT INTO TBA_DRIVERS (EMPLOYEE_NUMBER,FULLNAME) VALUES ('1603111351299','Barclay Adkins');
INSERT INTO TBA_DRIVERS (EMPLOYEE_NUMBER,FULLNAME) VALUES ('1626030899099','Lawrence Daniels');
INSERT INTO TBA_DRIVERS (EMPLOYEE_NUMBER,FULLNAME) VALUES ('1614062730299','Berk Sims');
INSERT INTO TBA_DRIVERS (EMPLOYEE_NUMBER,FULLNAME) VALUES ('1646071944799','Aquila Hill');
INSERT INTO TBA_DRIVERS (EMPLOYEE_NUMBER,FULLNAME) VALUES ('1694011495399','Colton Bush');
INSERT INTO TBA_DRIVERS (EMPLOYEE_NUMBER,FULLNAME) VALUES ('1629070870399','Anthony Palmer');
INSERT INTO TBA_DRIVERS (EMPLOYEE_NUMBER,FULLNAME) VALUES ('1639062859199','Martin Gibbs');
INSERT INTO TBA_DRIVERS (EMPLOYEE_NUMBER,FULLNAME) VALUES ('1631102809599','Nathaniel West');
INSERT INTO TBA_DRIVERS (EMPLOYEE_NUMBER,FULLNAME) VALUES ('1666121995399','Clark Maynard');
INSERT INTO TBA_DRIVERS (EMPLOYEE_NUMBER,FULLNAME) VALUES ('1631060101699','Trevor Casey');
INSERT INTO TBA_DRIVERS (EMPLOYEE_NUMBER,FULLNAME) VALUES ('1696012067699','Hop Reilly');
INSERT INTO TBA_DRIVERS (EMPLOYEE_NUMBER,FULLNAME) VALUES ('1627060110399','Kuame Fields');
INSERT INTO TBA_DRIVERS (EMPLOYEE_NUMBER,FULLNAME) VALUES ('1634092422499','Noble Ray');
INSERT INTO TBA_DRIVERS (EMPLOYEE_NUMBER,FULLNAME) VALUES ('1609072771499','Paul Winters');
INSERT INTO TBA_DRIVERS (EMPLOYEE_NUMBER,FULLNAME) VALUES ('1644080710399','Holmes Kemp');
INSERT INTO TBA_DRIVERS (EMPLOYEE_NUMBER,FULLNAME) VALUES ('1636050304099','Allistair Yang');
INSERT INTO TBA_DRIVERS (EMPLOYEE_NUMBER,FULLNAME) VALUES ('1627040672699','Cooper Mccarty');
INSERT INTO TBA_DRIVERS (EMPLOYEE_NUMBER,FULLNAME) VALUES ('1653080229999','Joel Stout');
INSERT INTO TBA_DRIVERS (EMPLOYEE_NUMBER,FULLNAME) VALUES ('1611032448499','Aquila Mcleod');
INSERT INTO TBA_DRIVERS (EMPLOYEE_NUMBER,FULLNAME) VALUES ('1658081360699','Elmo Black');
INSERT INTO TBA_DRIVERS (EMPLOYEE_NUMBER,FULLNAME) VALUES ('1623092514999','Kadeem Johnston');


INSERT INTO TAB_TYPE_OF_TAB_VEHICLES (DESCRIPTION,SPECIAL_QUALIFICATION) VALUES ('Moped','N');
INSERT INTO TAB_TYPE_OF_TAB_VEHICLES (DESCRIPTION,SPECIAL_QUALIFICATION) VALUES ('Motorcycle','N');
INSERT INTO TAB_TYPE_OF_TAB_VEHICLES (DESCRIPTION,SPECIAL_QUALIFICATION) VALUES ('Trike motorcycle','S');
INSERT INTO TAB_TYPE_OF_TAB_VEHICLES (DESCRIPTION,SPECIAL_QUALIFICATION) VALUES ('Car','S');
INSERT INTO TAB_TYPE_OF_TAB_VEHICLES (DESCRIPTION,SPECIAL_QUALIFICATION) VALUES ('Light rigid heavy vehicle','S');
INSERT INTO TAB_TYPE_OF_TAB_VEHICLES (DESCRIPTION,SPECIAL_QUALIFICATION) VALUES ('Medium rigid heavy vehicle','S');
INSERT INTO TAB_TYPE_OF_TAB_VEHICLES (DESCRIPTION,SPECIAL_QUALIFICATION) VALUES ('Heavy rigid vehicle','S');
INSERT INTO TAB_TYPE_OF_TAB_VEHICLES (DESCRIPTION,SPECIAL_QUALIFICATION) VALUES ('Tractor','N');
INSERT INTO TAB_TYPE_OF_TAB_VEHICLES (DESCRIPTION,SPECIAL_QUALIFICATION) VALUES ('Wheelchair vehicle','S');


INSERT INTO TAB_VEHICLES (REGISTRATION_NUMBER,PLATE,STATUS,MILEAGE,MODEL,CURRENT_VALUE,REPLACEMENT_VALUE,
	TAXED_DATE,BOUGHT_DATE,POLICY_NUMBER,WRITTEN_OFF,ID_TAB_TYPES_OF_VEHICLES) 
		VALUES ('4410512','ABC123','Active','2500','2010','1000000','1500000',sysdate,sysdate,'446655885','N','1');---------------------
INSERT INTO TAB_VEHICLES (REGISTRATION_NUMBER,PLATE,STATUS,MILEAGE,MODEL,CURRENT_VALUE,REPLACEMENT_VALUE,
	TAXED_DATE,BOUGHT_DATE,POLICY_NUMBER,WRITTEN_OFF,ID_TAB_TYPES_OF_VEHICLES) 
		VALUES ('32210512','ABC753','Active','4500','2014','4000000','900000',sysdate,sysdate,'446444885','N','2');		
INSERT INTO TAB_VEHICLES (REGISTRATION_NUMBER,PLATE,STATUS,MILEAGE,MODEL,CURRENT_VALUE,REPLACEMENT_VALUE,
	TAXED_DATE,BOUGHT_DATE,POLICY_NUMBER,WRITTEN_OFF,ID_TAB_TYPES_OF_VEHICLES) 
		VALUES ('5450512','ABC456','Active','7500','2014','3000000','800000',sysdate,sysdate,'410655885','N','3');
INSERT INTO TAB_VEHICLES (REGISTRATION_NUMBER,PLATE,STATUS,MILEAGE,MODEL,CURRENT_VALUE,REPLACEMENT_VALUE,
	TAXED_DATE,BOUGHT_DATE,POLICY_NUMBER,WRITTEN_OFF,ID_TAB_TYPES_OF_VEHICLES) 
		VALUES ('45550512','ABC789','Inactive','8500','2011','2000000','700000',sysdate,sysdate,'776655885','N','4');
INSERT INTO TAB_VEHICLES (REGISTRATION_NUMBER,PLATE,STATUS,MILEAGE,MODEL,CURRENT_VALUE,REPLACEMENT_VALUE,
	TAXED_DATE,BOUGHT_DATE,POLICY_NUMBER,WRITTEN_OFF,ID_TAB_TYPES_OF_VEHICLES) 
		VALUES ('5245454','ABC224','Sold','12500','2011','2002000','1000000',sysdate,sysdate,'886655885','N','5');
INSERT INTO TAB_VEHICLES (REGISTRATION_NUMBER,PLATE,STATUS,MILEAGE,MODEL,CURRENT_VALUE,REPLACEMENT_VALUE,
	TAXED_DATE,BOUGHT_DATE,POLICY_NUMBER,WRITTEN_OFF,ID_TAB_TYPES_OF_VEHICLES) 
		VALUES ('445105412','XXX123','Active','2100','2011','3000000','400000',sysdate,sysdate,'446655445','N','6');		
INSERT INTO TAB_VEHICLES (REGISTRATION_NUMBER,PLATE,STATUS,MILEAGE,MODEL,CURRENT_VALUE,REPLACEMENT_VALUE,
	TAXED_DATE,BOUGHT_DATE,POLICY_NUMBER,WRITTEN_OFF,ID_TAB_TYPES_OF_VEHICLES) 
		VALUES ('45445352','YYY123','Active','500','2011','800000','600000',sysdate,sysdate,'444654775','S','7');
INSERT INTO TAB_VEHICLES (REGISTRATION_NUMBER,PLATE,STATUS,MILEAGE,MODEL,CURRENT_VALUE,REPLACEMENT_VALUE,
	TAXED_DATE,BOUGHT_DATE,POLICY_NUMBER,WRITTEN_OFF,ID_TAB_TYPES_OF_VEHICLES) 
		VALUES ('665657','CSD123','Active','457','2011','400000','700000',sysdate,sysdate,'104255885','N','8');
INSERT INTO TAB_VEHICLES (REGISTRATION_NUMBER,PLATE,STATUS,MILEAGE,MODEL,CURRENT_VALUE,REPLACEMENT_VALUE,
	TAXED_DATE,BOUGHT_DATE,POLICY_NUMBER,WRITTEN_OFF,ID_TAB_TYPES_OF_VEHICLES) 
		VALUES ('4557575','SSA123','Sold','665','2013','700000','800000',sysdate,sysdate,'201455885','N','9');
INSERT INTO TAB_VEHICLES (REGISTRATION_NUMBER,PLATE,STATUS,MILEAGE,MODEL,CURRENT_VALUE,REPLACEMENT_VALUE,
	TAXED_DATE,BOUGHT_DATE,POLICY_NUMBER,WRITTEN_OFF,ID_TAB_TYPES_OF_VEHICLES) 
		VALUES ('56453345','FFF123','Active','5665','2014','1200000','1200000',sysdate,sysdate,'201755885','N','9');
INSERT INTO TAB_VEHICLES (REGISTRATION_NUMBER,PLATE,STATUS,MILEAGE,MODEL,CURRENT_VALUE,REPLACEMENT_VALUE,
	TAXED_DATE,BOUGHT_DATE,POLICY_NUMBER,WRITTEN_OFF,ID_TAB_TYPES_OF_VEHICLES) 
		VALUES ('7757545','YTY123','Active','7588','2014','1200000','1300000',sysdate,sysdate,'201054485','N','8');
INSERT INTO TAB_VEHICLES (REGISTRATION_NUMBER,PLATE,STATUS,MILEAGE,MODEL,CURRENT_VALUE,REPLACEMENT_VALUE,
	TAXED_DATE,BOUGHT_DATE,POLICY_NUMBER,WRITTEN_OFF,ID_TAB_TYPES_OF_VEHICLES) 
		VALUES ('787524124','GGG123','Active','7896','2014','1300000','1300000',sysdate,sysdate,'446654258','N','7');
INSERT INTO TAB_VEHICLES (REGISTRATION_NUMBER,PLATE,STATUS,MILEAGE,MODEL,CURRENT_VALUE,REPLACEMENT_VALUE,
	TAXED_DATE,BOUGHT_DATE,POLICY_NUMBER,WRITTEN_OFF,ID_TAB_TYPES_OF_VEHICLES) 
		VALUES ('5875454','VVV123','Sold','1263','2015','1400000','1300000',sysdate,sysdate,'146654477','S','6');
INSERT INTO TAB_VEHICLES (REGISTRATION_NUMBER,PLATE,STATUS,MILEAGE,MODEL,CURRENT_VALUE,REPLACEMENT_VALUE,
	TAXED_DATE,BOUGHT_DATE,POLICY_NUMBER,WRITTEN_OFF,ID_TAB_TYPES_OF_VEHICLES) 
		VALUES ('8642456','MMM128','Active','1200','2015','1500000','1400000',sysdate,sysdate,'246622825','N','5');
INSERT INTO TAB_VEHICLES (REGISTRATION_NUMBER,PLATE,STATUS,MILEAGE,MODEL,CURRENT_VALUE,REPLACEMENT_VALUE,
	TAXED_DATE,BOUGHT_DATE,POLICY_NUMBER,WRITTEN_OFF,ID_TAB_TYPES_OF_VEHICLES) 
		VALUES ('5454242','QQQ128','Active','1474','2015','1600000','1400000',sysdate,sysdate,'336655335','N','4');
INSERT INTO TAB_VEHICLES (REGISTRATION_NUMBER,PLATE,STATUS,MILEAGE,MODEL,CURRENT_VALUE,REPLACEMENT_VALUE,
	TAXED_DATE,BOUGHT_DATE,POLICY_NUMBER,WRITTEN_OFF,ID_TAB_TYPES_OF_VEHICLES) 
		VALUES ('2828282','TTT124','Active','1598','2017','1700000','1000000',sysdate,sysdate,'776657785','N','3');
INSERT INTO TAB_VEHICLES (REGISTRATION_NUMBER,PLATE,STATUS,MILEAGE,MODEL,CURRENT_VALUE,REPLACEMENT_VALUE,
	TAXED_DATE,BOUGHT_DATE,POLICY_NUMBER,WRITTEN_OFF,ID_TAB_TYPES_OF_VEHICLES) 
		VALUES ('3363635','PPP188','Inactive','12450','2016','500000','1000000',sysdate,sysdate,'996655899','S','2');
INSERT INTO TAB_VEHICLES (REGISTRATION_NUMBER,PLATE,STATUS,MILEAGE,MODEL,CURRENT_VALUE,REPLACEMENT_VALUE,
	TAXED_DATE,BOUGHT_DATE,POLICY_NUMBER,WRITTEN_OFF,ID_TAB_TYPES_OF_VEHICLES) 
		VALUES ('74542420','LLL127','Active','15000','2015','450000','1000000',sysdate,sysdate,'336655833','N','1');
INSERT INTO TAB_VEHICLES (REGISTRATION_NUMBER,PLATE,STATUS,MILEAGE,MODEL,CURRENT_VALUE,REPLACEMENT_VALUE,
	TAXED_DATE,BOUGHT_DATE,POLICY_NUMBER,WRITTEN_OFF,ID_TAB_TYPES_OF_VEHICLES) 
		VALUES ('10444450','ASD124','Active','12555','2014','1200000','1300000',sysdate,sysdate,'386655838','N','1');
INSERT INTO TAB_VEHICLES (REGISTRATION_NUMBER,PLATE,STATUS,MILEAGE,MODEL,CURRENT_VALUE,REPLACEMENT_VALUE,
	TAXED_DATE,BOUGHT_DATE,POLICY_NUMBER,WRITTEN_OFF,ID_TAB_TYPES_OF_VEHICLES) 
		VALUES ('45400004','LKL173','Active','17000','2013','1300000','1200000',sysdate,sysdate,'436655839','N','2');
INSERT INTO TAB_VEHICLES (REGISTRATION_NUMBER,PLATE,STATUS,MILEAGE,MODEL,CURRENT_VALUE,REPLACEMENT_VALUE,
	TAXED_DATE,BOUGHT_DATE,POLICY_NUMBER,WRITTEN_OFF,ID_TAB_TYPES_OF_VEHICLES) 
		VALUES ('40404058','PKP153','Active','18050','2011','1400000','1100000',sysdate,sysdate,'446655400','S','3');
INSERT INTO TAB_VEHICLES (REGISTRATION_NUMBER,PLATE,STATUS,MILEAGE,MODEL,CURRENT_VALUE,REPLACEMENT_VALUE,
	TAXED_DATE,BOUGHT_DATE,POLICY_NUMBER,WRITTEN_OFF,ID_TAB_TYPES_OF_VEHICLES) 
		VALUES ('7721400','IUI523','Active','14500','2012','1500000','4400000',sysdate,sysdate,'400655885','N','4');


INSERT INTO TAB_TYPES_TAB_SERVICES (DESCRIPTION) VALUES ('Automatic Transmission Fluid');
INSERT INTO TAB_TYPES_TAB_SERVICES (DESCRIPTION) VALUES ('Battery and Cables');
INSERT INTO TAB_TYPES_TAB_SERVICES (DESCRIPTION) VALUES ('Belts');
INSERT INTO TAB_TYPES_TAB_SERVICES (DESCRIPTION) VALUES ('Brakes');
INSERT INTO TAB_TYPES_TAB_SERVICES (DESCRIPTION) VALUES ('Cabin Air Filter');
INSERT INTO TAB_TYPES_TAB_SERVICES (DESCRIPTION) VALUES ('Chassis Lubrication');
INSERT INTO TAB_TYPES_TAB_SERVICES (DESCRIPTION) VALUES ('Dashboard Indicator Light On');
INSERT INTO TAB_TYPES_TAB_SERVICES (DESCRIPTION) VALUES ('Coolant (Antifreeze)');
INSERT INTO TAB_TYPES_TAB_SERVICES (DESCRIPTION) VALUES ('Engine Air Filter');
INSERT INTO TAB_TYPES_TAB_SERVICES (DESCRIPTION) VALUES ('Engine Oil');
INSERT INTO TAB_TYPES_TAB_SERVICES (DESCRIPTION) VALUES ('Exhaust');
INSERT INTO TAB_TYPES_TAB_SERVICES (DESCRIPTION) VALUES ('Hoses');
INSERT INTO TAB_TYPES_TAB_SERVICES (DESCRIPTION) VALUES ('Lights');
INSERT INTO TAB_TYPES_TAB_SERVICES (DESCRIPTION) VALUES ('Power Steering Fluid');
INSERT INTO TAB_TYPES_TAB_SERVICES (DESCRIPTION) VALUES ('Steering and Suspension');
INSERT INTO TAB_TYPES_TAB_SERVICES (DESCRIPTION) VALUES ('Tire Inflation and Condition');
INSERT INTO TAB_TYPES_TAB_SERVICES (DESCRIPTION) VALUES ('Wheel Alignment');
INSERT INTO TAB_TYPES_TAB_SERVICES (DESCRIPTION) VALUES ('Windshield Washer Fluid');
INSERT INTO TAB_TYPES_TAB_SERVICES (DESCRIPTION) VALUES ('Wiper Blades');


INSERT INTO TAB_INSURANCE_CLAIMS (ID_VEHICLE,POLICY,LOSS_DATE,ISSUE_DATE,NATURE_PAYMENT,DAMAGES) 
	VALUES ('1','444777',sysdate,sysdate,'Credit card','Stop, wheels');
INSERT INTO TAB_INSURANCE_CLAIMS (ID_VEHICLE,POLICY,LOSS_DATE,ISSUE_DATE,NATURE_PAYMENT,DAMAGES) 
	VALUES ('2','444778',sysdate,sysdate,'Credit card','Stop, wheels');
INSERT INTO TAB_INSURANCE_CLAIMS (ID_VEHICLE,POLICY,LOSS_DATE,ISSUE_DATE,NATURE_PAYMENT,DAMAGES) 
	VALUES ('3','444454',sysdate,sysdate,'Credit card','Wheels and paint');
INSERT INTO TAB_INSURANCE_CLAIMS (ID_VEHICLE,POLICY,LOSS_DATE,ISSUE_DATE,NATURE_PAYMENT,DAMAGES) 
	VALUES ('1','444585',sysdate,sysdate,'Credit card','Wheels');
INSERT INTO TAB_INSURANCE_CLAIMS (ID_VEHICLE,POLICY,LOSS_DATE,ISSUE_DATE,NATURE_PAYMENT,DAMAGES) 
	VALUES ('1','444969',sysdate,sysdate,'Credit card','Stop');
INSERT INTO TAB_INSURANCE_CLAIMS (ID_VEHICLE,POLICY,LOSS_DATE,ISSUE_DATE,NATURE_PAYMENT,DAMAGES) 
	VALUES ('4','444869',sysdate,sysdate,'Credit card','Stop, wheels');
INSERT INTO TAB_INSURANCE_CLAIMS (ID_VEHICLE,POLICY,LOSS_DATE,ISSUE_DATE,NATURE_PAYMENT,DAMAGES) 
	VALUES ('15','444125',sysdate,sysdate,'Credit card','Stop, wheels');
INSERT INTO TAB_INSURANCE_CLAIMS (ID_VEHICLE,POLICY,LOSS_DATE,ISSUE_DATE,NATURE_PAYMENT,DAMAGES) 
	VALUES ('17','444000',sysdate,sysdate,'Credit card','Lights');
INSERT INTO TAB_INSURANCE_CLAIMS (ID_VEHICLE,POLICY,LOSS_DATE,ISSUE_DATE,NATURE_PAYMENT,DAMAGES) 
	VALUES ('20','444010',sysdate,sysdate,'Credit card','Stop, wheels');
INSERT INTO TAB_INSURANCE_CLAIMS (ID_VEHICLE,POLICY,LOSS_DATE,ISSUE_DATE,NATURE_PAYMENT,DAMAGES) 
	VALUES ('3','444104',sysdate,sysdate,'Credit card','Paint');
	

INSERT INTO TAB_REPAIR_COSTS (ID_VEHICLE,REPAIR_DATE,DESCRIPTION,AMOUNT,STATUS) 
	VALUES ('1',sysdate,'Working on it','15000','Paid');
INSERT INTO TAB_REPAIR_COSTS (ID_VEHICLE,REPAIR_DATE,DESCRIPTION,AMOUNT,STATUS) 
	VALUES ('2',sysdate,'Working on it','17000','Pending');
INSERT INTO TAB_REPAIR_COSTS (ID_VEHICLE,REPAIR_DATE,DESCRIPTION,AMOUNT,STATUS) 
	VALUES ('2',sysdate,'Working on it','10000','Paid');
INSERT INTO TAB_REPAIR_COSTS (ID_VEHICLE,REPAIR_DATE,DESCRIPTION,AMOUNT,STATUS) 
	VALUES ('15',sysdate,'Working on it','15500','Pending');


INSERT INTO TAB_SERVICES (ID_VEHICLE,NAME,ISSUE_DATE,DESCRIPTION,STATUS) 
	VALUES ('3','Mandatory 9000_service service; current mileage 9123',sysdate,'','Pending');
INSERT INTO TAB_SERVICES (ID_VEHICLE,NAME,ISSUE_DATE,DESCRIPTION,STATUS) 
	VALUES ('20','Mandatory 3000_service service; current mileage 3500',sysdate,'','Pending');
INSERT INTO TAB_SERVICES (ID_VEHICLE,NAME,ISSUE_DATE,DESCRIPTION,STATUS) 
	VALUES ('17','Mandatory 3000_service service; current mileage 3804',sysdate,'','Ok');
INSERT INTO TAB_SERVICES (ID_VEHICLE,NAME,ISSUE_DATE,DESCRIPTION,STATUS) 
	VALUES ('2','Mandatory 6000_service service; current mileage 7588',sysdate,'','Scheduled');
INSERT INTO TAB_SERVICES (ID_VEHICLE,NAME,ISSUE_DATE,DESCRIPTION,STATUS) 
	VALUES ('10','Mandatory 3000_service service; current mileage 3250',sysdate,'','Scheduled');


INSERT INTO TAB_TAB_SERVICES_DETAILS (ID_TAB_SERVICES,TYPES_SERVICE,STATUS) VALUES ('1','1','Pending');
INSERT INTO TAB_TAB_SERVICES_DETAILS (ID_TAB_SERVICES,TYPES_SERVICE,STATUS) VALUES ('1','4','Observations');
INSERT INTO TAB_TAB_SERVICES_DETAILS (ID_TAB_SERVICES,TYPES_SERVICE,STATUS) VALUES ('2','4','Needs Repair');
INSERT INTO TAB_TAB_SERVICES_DETAILS (ID_TAB_SERVICES,TYPES_SERVICE,STATUS) VALUES ('2','3','Needs Repair');
INSERT INTO TAB_TAB_SERVICES_DETAILS (ID_TAB_SERVICES,TYPES_SERVICE,STATUS) VALUES ('3','9','Needs Repair');
INSERT INTO TAB_TAB_SERVICES_DETAILS (ID_TAB_SERVICES,TYPES_SERVICE,STATUS) VALUES ('3','5','Observations');
INSERT INTO TAB_TAB_SERVICES_DETAILS (ID_TAB_SERVICES,TYPES_SERVICE,STATUS) VALUES ('4','2','Ok');
INSERT INTO TAB_TAB_SERVICES_DETAILS (ID_TAB_SERVICES,TYPES_SERVICE,STATUS) VALUES ('4','8','Pending');
INSERT INTO TAB_TAB_SERVICES_DETAILS (ID_TAB_SERVICES,TYPES_SERVICE,STATUS) VALUES ('5','2','Ok');
INSERT INTO TAB_TAB_SERVICES_DETAILS (ID_TAB_SERVICES,TYPES_SERVICE,STATUS) VALUES ('5','4','Pending');